### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [LorddBaelish/deep-video-activity-recognition#1]
Can you please share the pretrained model sports1M_weights.h5?

**Comment by aegorfk** [comment]
> Can you please share the pretrained model sports1M_weights.h5?

Download here: https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2

**Comment by Zumbalamambo** [comment]
@aegorfk thanks
